### ISSUE TITLE
POSTCAPITALIST

### ISSUE THREAD

**Issue by razumv** [bitsongofficial/delegation-program#46]
### Validator address

bitsongvaloper1slnkc2a8lhxgz5cc7lg9zlgzfedfpdve0rh2p6

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

**razumv | DOUBLE TOP 🇺🇦#4876/@razumv/KURASH#7375/@kuraassh**

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, Running an public rpc/api

### Details

Professional validators. Supported Bitsong. Fast upgrades and good reaction. Take part in gov

https://explorer.postcapitalist.io/bitsong/staking/bitsongvaloper1slnkc2a8lhxgz5cc7lg9zlgzfedfpdve0rh2p6

https://blog.postcapitalist.io/introducing-validator-postcapitalist/
https://blog.postcapitalist.io/roadmap/
https://blog.postcapitalist.io/charity-validator-postcapitalist-beginning/

### Goals

Goals long-term participation in the project, active governance, spred info about Bitsong, create content , and support in social media!

**Comment by ctrl-Felix** [comment]
Score: 1691 (temp)
https://l.ctrl-felix.de/2Xyqx

Please note: Your mintscan logo is missing which is a requirement to get a delegation. Please update this to get the delegation.
Furthermore, do you have a target for the comission restaking? If so please write it here too so that I can adapt the calculation. Otherwise we take the default value of 40%

**Comment by razumv** [comment]
@ctrl-Felix ОК. We will upload an image today. Regarding the redelegation - we will restake at least 60%

**Comment by ctrl-Felix** [comment]
Okay, new Score then: 1869
https://l.ctrl-felix.de/ZEBzy
